services:

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: flask_database
      MYSQL_USER: usuario
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./db_data:/var/lib/mysql
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: usuario
      PMA_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mariadb

  web:
    container_name: saw-web
    image: agsalguero/saw:latest
    ports:
      - "5004:5000"
    volumes:
      - ./web:/app
    environment:
      FLASK_ENV: development

  apirest:
    container_name: api-rest
    image: agsalguero/saw:latest
    ports:
      - "5007:5000"
    volumes:
      - ./api:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - mariadb

    
  chat:
    container_name: microchat
    image: agsalguero/saw:latest
    ports:
      - "5001:5000"
    volumes:
      - ./chat:/app
    environment:
      FLASK_ENV: development
    depends_on:
      - web
